base_url = "https://cleberg.io"
title = "Christian Cleberg"
description = "A collection of my thoughts and musings."
generate_feed = true
minify_html = true

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
render_emoji = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "dracula", filename = "syntax-theme.css" },
]

[extra]
title_separator = "|"
