base_url = "https://cleberg.io"
title = "Christian Cleberg"
compile_sass = false
build_search_index = false
generate_feed = true
description = "A collection of my thoughts and musings."

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]
render_emoji = true

[extra]
title_separator = "|"