base_url = "https://cleberg.io"
default_language = "en"

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
render_emoji = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]

[extra]
title_separator = "|"

[languages.en]
title = "Christian Cleberg"
description = "A collection of my thoughts and musings."
generate_feed = true

[languages.es]
title = "Christian Cleberg"
description = "Una colección de mis pensamientos y reflexiones."
generate_feed = false