base_url = "https://cleberg.io"
title = "Christian Cleberg"
description = "A collection of my thoughts and musings."
default_language = "en"
generate_feed = true

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
render_emoji = true

[extra]
title_separator = "|"